workflows:
  android_apk:
    name: Android APK (Amazon)
    max_build_duration: 60

    environment:
      node: 20
      java: 17

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Build web
        script: |
          npm run build

      - name: Add Android platform if missing
        script: |
          if [ ! -d "android" ]; then
            npx cap add android
          fi

      - name: Sync Capacitor
        script: |
          npx cap sync android

      - name: Fix gradlew permissions
        script: |
          chmod +x android/gradlew

      - name: Build Debug APK
        script: |
          cd android
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/reports/**
